test darwin

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -90,14 +90,14 @@ jobs:
         softwareupdate --all --install --force
         sudo xcode-select --install
 
-    # https://github.com/actions/runner/issues/1456#issue-1042407558
-    - name: install and launch docker
-      run: |
-        HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
-        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
-        open -a /Applications/Docker.app --args --unattended --accept-license
-        echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
-        while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+    # # https://github.com/actions/runner/issues/1456#issue-1042407558
+    # - name: install and launch docker
+    #   run: |
+    #     HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+    #     sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+    #     open -a /Applications/Docker.app --args --unattended --accept-license
+    #     echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+    #     while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
 
     - name: Run Bazel Cache server
       run: |
