test darwin

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -72,6 +72,78 @@ jobs:
         path: |
           build/**/envoy/*.tar.gz
 
+  build_envoy_darwin_amd64:
+    runs-on: macos-latest
+    steps:
+    - name: Checkout step
+      id: checkout
+      uses: actions/checkout@v2
+
+    # https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#quick-start-bazel-build-for-developers
+    - name: install common deps
+      run: | 
+        brew install coreutils automake ninja clang-format
+        
+    - name: install full xcode
+      run: |
+        sudo rm -rf /Library/Developer/CommandLineTools
+        softwareupdate --all --install --force
+        sudo xcode-select --install
+
+    # https://github.com/actions/runner/issues/1456#issue-1042407558
+    - name: install and launch docker
+      run: |
+        HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+        open -a /Applications/Docker.app --args --unattended --accept-license
+        echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+        while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+
+    - name: Run Bazel Cache server
+      run: |
+        CONTAINER_ID=$(docker run -dt \
+          -e BAZEL_REMOTE_S3_AUTH_METHOD=access_key \
+          -e BAZEL_REMOTE_S3_BUCKET=${{secrets.AWS_BAZEL_CACHE_S3_BUCKET}} \
+          -e BAZEL_REMOTE_S3_ACCESS_KEY_ID=${{secrets.AWS_BAZEL_CACHE_ACCESS_KEY}} \
+          -e BAZEL_REMOTE_S3_SECRET_ACCESS_KEY=${{secrets.AWS_BAZEL_CACHE_SECRET_KEY}} \
+          -e BAZEL_REMOTE_S3_REGION=us-east-2 \
+          -e BAZEL_REMOTE_ACCESS_LOG_LEVEL=all \
+          -e BAZEL_REMOTE_S3_ENDPOINT=s3.us-east-2.amazonaws.com \
+          -e BAZEL_REMOTE_DIR=/data \
+          -e BAZEL_REMOTE_S3_PREFIX=envoy/darwin-latest \
+          -p 9092:9092 \
+          -p 8080:8080 \
+          buchgr/bazel-remote-cache)
+        echo "REMOTE_CACHE_SEVER_IP=$(docker inspect $CONTAINER_ID | jq -r '.[].NetworkSettings.Networks.bridge.IPAddress')" >> $GITHUB_ENV
+    
+
+    - name: make build darwin
+      run: make build/envoy
+      env:
+        GOOS: darwin
+        GOARCH: amd64
+        ENVOY_DISTRO: darwin
+        BUILD_ENVOY_FROM_SOURCES: true
+        ENVOY_TAG: ${{ github.event.inputs.envoyTag }}
+        REMOTE_CACHE_SEVER_HOSTNAME: bazel-remote-server-darwin
+        REMOTE_CACHE_SEVER_IP: ${{env.REMOTE_CACHE_SEVER_IP}}
+
+    - name: Zip artifact
+      run: |
+        if [[ -f build/artifacts-darwin-amd64/envoy/envoy-${envoyTag#v}-darwin ]]; then  
+            tar -czvf build/artifacts-darwin-amd64/envoy/envoy-${envoyTag#v}-darwin.tar.gz build/artifacts-darwin-amd64/envoy/envoy-${envoyTag#v}-darwin
+        fi
+      env:
+        envoyTag: ${{ github.event.inputs.envoyTag }}
+
+    - name: Save artifact
+      uses: actions/upload-artifact@v3
+      id: save_artifacts
+      with:
+        name: artifacts
+        path: |
+          build/**/envoy/*.tar.gz
+
 # jobs:
 #   build_envoy_alpine_amd64:
 #     runs-on: ubuntu-18.04
